FROM quay.io/ethcscs/ompi:5.0.7-ofi1.15-cuda12.8

# Install system dependencies
RUN apt-get update && apt-get install -y   \
        unzip                       \
        libopenblas-dev             \
        liblapack-dev               \
        python3-dev                 \
        python3-pip                 \
	libmetis-dev                \
        --no-install-recommends     \
  && rm -rf /var/lib/apt/lists/*    \
  && rm -rf /usr/lib/python3.12/EXTERNALLY-MANAGED
    
# Download and compile HDF5 with MPI
ARG HDF5_VERSION=1.14.6
RUN wget -q https://github.com/HDFGroup/hdf5/releases/download/hdf5_${HDF5_VERSION}/hdf5-${HDF5_VERSION}.tar.gz \
    && tar -xzf hdf5-${HDF5_VERSION}.tar.gz \
    && cd hdf5-${HDF5_VERSION} \
    && CC=mpicc ./configure --prefix=/usr --enable-parallel --enable-shared \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. && rm -rf hdf5-${HDF5_VERSION}*

# Install libxsmm
RUN git clone https://github.com/libxsmm/libxsmm.git \
    && cd libxsmm \
    && make -j4 STATIC=0 BLAS=0 \
    && cd ..    

ENV PYFR_XSMM_LIBRARY_PATH=/libxsmm/lib/libxsmm.so

# Install h5py with MPI
RUN ldconfig /usr/local/cuda/targets/sbsa-linux/lib/stubs \
    && HDF5_MPI="ON" CC=mpicc pip install --no-cache-dir --no-binary=h5py h5py \
    && ldconfig

# Set base directory for pyCUDA cache
ENV XDG_CACHE_HOME /tmp

# Install PyFR
RUN pip install pyfr==2.1 
