FROM ghcr.io/sarus-suite/containerfiles-ci/comm-fwk:ofi2.6.0-ucx1.22.0

ARG MPICH_VER=5.0.1
RUN wget -q https://www.mpich.org/static/downloads/${MPICH_VER}/mpich-${MPICH_VER}.tar.gz \
    && tar xf mpich-${MPICH_VER}.tar.gz \
    && cd mpich-${MPICH_VER} \
    && ./autogen.sh \
    && ./configure --prefix=/usr --enable-fast=O3,ndebug \
       --disable-cxx --with-xpmem=/usr \
       --with-device=ch4:ofi --with-libfabric=/usr \
       --with-cuda=/usr/local/cuda \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf mpich-${MPICH_VER}.tar.gz mpich-${MPICH_VER}

LABEL org.opencontainers.image.ref.name="mpich"
LABEL org.opencontainers.image.version="${MPICH_VER}-ofi2.6.0"
