FROM docker.io/library/debian:bookworm

ARG LIBFABRIC_VERSION=1.15.1
ARG MPI_VERSION=5.0.7
ARG MPI_SHORT_VERSION=5.0

RUN apt-get update \
    && apt-get install -y \
      build-essential \
      automake \
      autoconf \
      libtool \
      file \
      g++ \
      gcc \
      gfortran \
      make \
      gdb \
      wget \
      git \
      python3 \
      python3-dev \
      python3-pip \
      gawk \
      ssh \
      --no-install-recommends \
    && ln -s /usr/bin/python3-config /usr/bin/python-config \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install libfabric
RUN wget -q https://github.com/ofiwg/libfabric/archive/v${LIBFABRIC_VERSION}.tar.gz \
    && tar xf v${LIBFABRIC_VERSION}.tar.gz \
    && cd libfabric-${LIBFABRIC_VERSION} \
    && ./autogen.sh \
    && ./configure --prefix=/usr \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf v${LIBFABRIC_VERSION}.tar.gz libfabric-${LIBFABRIC_VERSION}

# Install OpenMPI
RUN wget -q https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${MPI_VERSION}.tar.gz \
    && tar xf openmpi-${MPI_VERSION}.tar.gz \
    && cd openmpi-${MPI_VERSION} \
    && ./configure --prefix=/usr --with-ofi=/usr \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf openmpi-${MPI_VERSION}.tar.gz openmpi-${MPI_VERSION}

RUN pip install mpi4py --break-system-packages

ENV LD_LIBRARY_PATH /pynamic/pynamic-pyMPI-2.6a1:${LD_LIBRARY_PATH}
ENV CC cc

RUN git clone https://github.com/madeeks/pynamic.git \
    && cd pynamic/pynamic-pyMPI-2.6a1 \
    && git checkout fixes \
    && python3 config_pynamic.py 495 1850 -e -u 215 1850 -n 100 -n 4 --with-python=python3 --with-mpi4py \
    && rm libmodule*.c libmodule*.o libutility*.c libutility*.h libutility*.o
    
    
    
#    && python3 config_pynamic.py 495 1850 -e -u 215 1850 -n 100 -n 4 --with-python=python3 --with-mpi4py

