FROM ghcr.io/sarus-suite/containerfiles-ci/ompi:5.0.9-ofi1.22-cuda12.8.1

# Download and compile HDF5 with MPI
ARG HDF5_VERSION=2.1.1
RUN wget -q https://github.com/HDFGroup/hdf5/releases/download/${HDF5_VERSION}/hdf5.tar.gz \
    && tar -xzf hdf5.tar.gz \
    && cd hdf5-${HDF5_VERSION} \
    && mkdir build && cd build \
    && cmake -DCMAKE_BUILD_TYPE=Release \
       -DCMAKE_C_COMPILER=mpicc \
       -DHDF5_ENABLE_PARALLEL=ON \
       -DBUILD_STATIC_LIBS=ON \
       -DBUILD_SHARED_LIBS=ON \
       -DHDF5_BUILD_FORTRAN=OFF \
       -DBUILD_TESTING=OFF \
       .. \
    && cmake --build . --config Release -j \
    && cmake --install . --prefix /usr \
    && ldconfig \
    && cd ../.. && rm -rf hdf5*

ARG sphexa_version=0.96.2
RUN git clone https://github.com/sphexa-org/sphexa.git \
    && cd sphexa \
    && git checkout v${sphexa_version} \
    && CC=mpicc CXX=mpicxx cmake -DCSTONE_WITH_GPU_AWARE_MPI=ON -DCMAKE_INSTALL_PREFIX=/usr . \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf sphexa

WORKDIR /sphexa

COPY ./wrapper.sh /sphexa/wrapper.sh

RUN wget -O /sphexa/50c.h5 https://zenodo.org/records/8369645/files/50c.h5?download=1 \
    && chmod a+x /sphexa/wrapper.sh

LABEL org.opencontainers.image.ref.name="sphexa"
LABEL org.opencontainers.image.version="${sphexa_version}-ompi5.0.9-ofi1.22-cuda12.8.1"
